### ISSUE TITLE
Make component frame resizale

### ISSUE THREAD

**Issue by khatabwedaa** [merakiui/merakiui#23]
The idea is to build a resizable frame to see how components are like in the different screen size

### 

Example

![resizable-div](https://user-images.githubusercontent.com/38974561/98712211-b1306880-238e-11eb-8de8-81e3171b742b.gif)

**Comment by khatabwedaa** [comment]
@viniciuskneves check it 🤗

**Comment by Arslan-Soomro** [comment]
Can I work on this ?

**Comment by khatabwedaa** [comment]
> Can I work on this ?

Yup off course @Arslan-Soomro

**Comment by Arslan-Soomro** [comment]
> > Can I work on this ?
> 
> Yup off course @Arslan-Soomro

can you point me where the source code for the div containing the component is located ?

**Comment by khatabwedaa** [comment]
https://github.com/merakiui/merakiui/blob/main/components/utilities/ViewComponent.vue

 Here

this slot <slot class="absolute top-0 left-0 w-full h-full" name="component"></slot>
