### ISSUE TITLE
Prettier as git hook

### ISSUE THREAD

**Issue by viniciuskneves** [merakiui/merakiui#24]
Hey @Miaababikir any specific reason for this workflow: https://github.com/merakiui/merakiui/blob/master/.github/workflows/format_prettier.yml ?

As far as I understood it is there to format the code only, right? If so, how about using git hooks to do so and the workflow just to actually check if the code has been formatted (could be useful for tests as well)?

This way, every time you commit it will fire Prettier and every time a PR is opened the lint check will be fired.

**Comment by khatabwedaa** [comment]
Hello @viniciuskneves is there any problem with this approach

**Comment by viniciuskneves** [comment]
Which problem do you mean?

**Comment by khatabwedaa** [comment]
The workflow approach

**Comment by viniciuskneves** [comment]
Well, it doesn't work for forks the way it is setup. The workflow could be fixed, it is an option, the other option is to setup it differently.

**Comment by khatabwedaa** [comment]
Aha Okay, no problem I will change it use it with git hooks.

**Comment by Miaababikir** [comment]
> Hey @Miaababikir any specific reason for this workflow: https://github.com/merakiui/merakiui/blob/master/.github/workflows/format_prettier.yml ?
> 
> As far as I understood it is there to format the code only, right? If so, how about using git hooks to do so and the workflow just to actually check if the code has been formatted (could be useful for tests as well)?
> 
> This way, every time you commit it will fire Prettier and every time a PR is opened the lint check will be fired.

Thanks Buddy, It's very convenient do set it up as you mention.

@khatabwedaa I will work on it.

**Comment by khatabwedaa** [comment]
Done 😃
