### ISSUE TITLE
Support theme

### ISSUE THREAD

**Issue by jellydn** [merakiui/merakiui#26]
## WHAT

- Support theme as https://mertjf.github.io/tailblocks/

## WHY

- Easy to migrate or integrate with different color

## HOW

- TBD

**Comment by khatabwedaa** [comment]
Hello @jellydn, I really think about this feature but the problem I have to change dark components to a light version like footers and about me components then I can add this feature If you have any suggestion for this tell me you an idea and how we can add dark/light components :smile:

**Comment by jellydn** [comment]
@khatabwedaa Have you checked out the tailwind v2? https://blog.tailwindcss.com/tailwindcss-v2 You could use `dark:` prefix to apply the theme.

**Comment by khatabwedaa** [comment]
Didn't check it yet but I will
