### ISSUE TITLE
Broken Link on Resources Page

### ISSUE THREAD

**Issue by flo-bananzki** [merakiui/merakiui#56]
Hey thanks for your awesome work. 
On your Page:
https://github.com/merakiui/merakiui/blob/7fba81aa8fe9e854bb52a4b8ee2ed94f9f1a6a59/pages/resources.vue#L13

the link is broken and refers to "/components", which probably should refers to "/#main"
Cheers

**Comment by khatabwedaa** [comment]
Fixed Thanks @flo-bananzki
