### ISSUE TITLE
Question about usage

### ISSUE THREAD

**Issue by NicolasLoew** [merakiui/merakiui#62]
Hey there,
I have a question about the general usage: So far, I have only used Tailwind CSS from CDN without setting up a build with CLI or similar.
Since I wanted to give MerakiUI a go, I installed nodeJS on my Windows 10 PC and run the commands from the readme:
`npm install
npm run dev`

In which folder/path is my index.html file now so I can get down to coding and using the MerakiUI snippets?
Or do I need to create an index.html file myself? 
http://localhost:3000 (where npm hot-reloads for development) just shows a clone of the MerakiUI website but as localhost. 

Re-phrasing: If I want to build a website using MerakiUI components do I actually need to clone&build this GitHub repo, or can I just setup a directy with a .html and .css file and import TailwindCSS via CDN and MerakiUI components will just work by default?
If I need to clone this repo and build it with npm to use MerakiUI components, where is the public facing folder in which I would have to create my index.html file?

Kind regards

**Comment by khatabwedaa** [comment]
Hi @NicolasLoew there are copy button on Meraki UI website you can copy the components with it the command on the read me it just for development if someone want to add new components new features, etc.
