### ISSUE TITLE
Are you familiar with the 0BSD license?

### ISSUE THREAD

**Issue by vhscom** [merakiui/merakiui#71]
Not long ago I worked with GitHub to add a new license which is perfect for projects where others are encouraged to copy-paste code—it's called the [BSD Zero Clause](https://choosealicense.com/licenses/0bsd/). If you haven't yet, please consider it as it contains no requirement to carry the license when the code is copied whereas the MIT license does.

Keep up the great work!

**Comment by khatabwedaa** [comment]
Thanks, I will check it
