### ISSUE TITLE
is merakiui.com down?

### ISSUE THREAD

**Issue by Ansub** [merakiui/merakiui#76]
i was opening merakiui.com today and i am getting this error today.

![CleanShot 2022-08-26 at 18 53 38](https://user-images.githubusercontent.com/12985873/186913565-c5b804a9-8c97-4d48-a109-e80747cade36.png)

**Comment by Chris-Agnew** [comment]
I'm getting the same error

**Comment by khatabwedaa** [comment]
Hi @Ansub we are working on some updates sorry for that we will be back as fast as we can.

Thanks.
