### ISSUE TITLE
all navbars except simple have a horizontal overflow when on mobile screen and the direction is RTL

### ISSUE THREAD

**Issue by iam-omer-mahdi** [merakiui/merakiui#80]
all Navbars except simple have a horizontal overflow when on mobile screen and the direction is RTL + categories Navbar menu button is visible on lg

**Comment by iam-omer-mahdi** [comment]
i fixed the issue on my fork at https://github.com/iam-omer-mahdi/merakiui

**Comment by khatabwedaa** [comment]
Thanks @iam-omer-mahdi, will fix it

**Comment by khatabwedaa** [comment]
Fixed!

**Comment by iam-omer-mahdi** [comment]
Thanks @khatabwedaa
