### ISSUE TITLE
merakiui.com is not responding.

### ISSUE THREAD

**Issue by yeasin-2002** [merakiui/merakiui#88]
Is merakiui.com is down for any reason? 
last few days I actually visited but it's not working. 

![image](https://github.com/merakiui/merakiui/assets/87494463/8e5c034a-ad6e-4c43-ad11-eb97ad52ff80)

**Comment by DevDhaif** [comment]
Thanks for reporting! Looks good on our end now (checked with [downforeveryoneorjustme.com](https://downforeveryoneorjustme.com/)). 
Can you try clearing your cache and cookies, or using a different browser? 
If still no luck, reply with more details about your issue.

**Comment by yeasin-2002** [comment]
@DevDhaif  Thanks, I got it. 
It's not working on my device. It required VPN.
